name: password_generator
description: "Password Generator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/passphraselist.txt
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
  ios: true
  web: true